# Generated by Django 5.0.2 on 2024-03-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ejemplo',
        ),
    ]
