# Generated by Django 5.0.2 on 2024-03-10 00:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origen', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='id unico para el libro en toda la biblioteca', primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='Died'),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Gabriel'),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='García Marquez'),
        ),
    ]
