# Generated by Django 5.0.2 on 2024-03-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origen', '0004_bookinstance_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
